# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(425, 183)
        Dialog.setAutoFillBackground(False)
        Dialog.setStyleSheet("background-color: #282828;")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(130, 0, 161, 41))
        self.label_4.setStyleSheet("color: #0077FF;\n"
"font: 5 22pt \"Century Gothic\";\n"
"")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(20, 10, 47, 13))
        self.label_5.setStyleSheet("color: #FFFFFF;\n"
"font: 5 8pt \"Century Gothic\";\n"
"")
        self.label_5.setObjectName("label_5")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(360, 160, 61, 16))
        self.label_3.setStyleSheet("color: #FFFFFF;\n"
"font: 5 8pt \"Century Gothic\";\n"
"")
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(10, 60, 151, 41))
        self.pushButton.setStyleSheet("color:#FFFFFF;\n"
"background-color: #0077FF;\n"
"border:none;\n"
"font: 5 12pt \"Century Gothic\";\n"
"border-radius:20px;")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 110, 101, 16))
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("color: #FFFFFF;\n"
"")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(290, 110, 81, 20))
        self.label_2.setStyleSheet("color: #FFFFFF;\n"
"")
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(250, 60, 151, 41))
        self.pushButton_2.setStyleSheet("color:#FFFFFF;\n"
"background-color: #0077FF;\n"
"border:none;\n"
"font: 5 12pt \"Century Gothic\";\n"
"border-radius:20px;")
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_4.setText(_translate("Dialog", "PyPassMan"))
        self.label_5.setText(_translate("Dialog", "By: ADN"))
        self.label_3.setText(_translate("Dialog", "version: 1.1"))
        self.pushButton.setText(_translate("Dialog", "Save"))
        self.label.setText(_translate("Dialog", "Tab for saving data"))
        self.label_2.setText(_translate("Dialog", "Data search tab"))
        self.pushButton_2.setText(_translate("Dialog", "Search"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
